name: Apply Kubernetes YAML

on:
  workflow_dispatch:
    inputs:
      rawYaml:
        description: 'Kubernetes YAML content to apply'
        required: true
        type: string

jobs:
  apply-kubernetes:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3


      # Step 4: Write the raw YAML input to a file
      - name: Write input YAML to file
        run: echo "${{ github.event.inputs.rawYaml }}" > ./manifest.yaml
      - name: apply to cluster
        uses: steebchen/kubectl@v2.0.0
        with: 
          config: ${{ secrets.KUBE_CONFIG }}
          command: apply --validate=false -f ./manifest.yaml 
